// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-cZW3AAHGw2FfbbA7AT7OZD2jjGdKtAI',
    appId: '1:193899665871:web:1e406d55432da555861aba',
    messagingSenderId: '193899665871',
    projectId: 'baas-vordlus',
    authDomain: 'baas-vordlus.firebaseapp.com',
    storageBucket: 'baas-vordlus.firebasestorage.app',
    measurementId: 'G-VL1909EXJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAANRyeQRlJUQiX4O9FX2l8t__zElCNx0',
    appId: '1:193899665871:android:4015aabb3794d2fb861aba',
    messagingSenderId: '193899665871',
    projectId: 'baas-vordlus',
    storageBucket: 'baas-vordlus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxx5zKuOYQEOe_H3iuoq5IxkWVH_9WtBA',
    appId: '1:193899665871:ios:c7e70de343d4847b861aba',
    messagingSenderId: '193899665871',
    projectId: 'baas-vordlus',
    storageBucket: 'baas-vordlus.firebasestorage.app',
    iosBundleId: 'com.example.baasVordlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxx5zKuOYQEOe_H3iuoq5IxkWVH_9WtBA',
    appId: '1:193899665871:ios:c7e70de343d4847b861aba',
    messagingSenderId: '193899665871',
    projectId: 'baas-vordlus',
    storageBucket: 'baas-vordlus.firebasestorage.app',
    iosBundleId: 'com.example.baasVordlus',
  );
}
